### ISSUE TITLE
Version of Prisma Cloud task

### ISSUE THREAD

**Issue by Simbec** [tkishel/pc_iac#11]
Hey, Tom. 

I think we'd need to update the azure-pipelines.yml to reference the version 3 of the Prisma Cloud Scan. they're currently as @2.
_"
steps:
  - task: Prisma Cloud IaC Scan@2
 "_

**Comment by tkishel** [comment]
Resolved via https://github.com/tkishel/pc_iac/commit/3bb7e7a38e568b5038e278b95936508621716b1d
But note that the Compute scan is failing for me when using an access/secret key instead of a username/password.
